<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<AssemblyTitle>The Aridity Team "Ascorbic" Library</AssemblyTitle>
	    <RootNamespace>AridityTeam</RootNamespace>
	    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	    <DocumentationFile>..\..\bin\$(Platform)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
	    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>
	
	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true' Or '$(TF_BUILD)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>
	
    <!--NuGet package info-->
    <PropertyGroup>
	    <PackageId>$(MSBuildProjectName)</PackageId>
		<PackageIcon>assets\ascorbic_icon.png</PackageIcon>
	    <Authors>PracticeMedicine;AridityTeam</Authors>
	    <Company>The Aridity Team</Company>
	    <PackageReadmeFile>README.md</PackageReadmeFile>
	    <Description>Platform core library for The Aridity Team projects.</Description>
	    <PackageTags>aridity;base;cereon;ide;core;utility;utilities;general</PackageTags>
		<PackageProjectUrl>https://aridityteam.github.io/ascorbic</PackageProjectUrl>
	    <RepositoryUrl>https://github.com/aridityteam/ascorbic</RepositoryUrl>
	    <PackageLicenseExpression>MIT</PackageLicenseExpression>
	    <Copyright>Copyright (c) 2025 The Aridity Team</Copyright>
	    <PublishRepositoryUrl>true</PublishRepositoryUrl>
	    <IncludeSymbols>true</IncludeSymbols>
	    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

	<PropertyGroup>
		<PackageReleaseNotes>
			I was supposed to release this version back then before I fly to an island for an staycation, but oh well:
			
			- Addition: MultiTextWriter.Writers
			- Addition: DisposableObject.Disposing event
			- Addition: BiDisposableObject.Disposing event
			- Addition: AsyncDisposableObject.Disposing event
			- Addition: DisposableObject.~DisposableObject
			- Addition: BiDisposableObject.~BiDisposableObject
			- Addition: AsyncDisposableObject.~AsyncDisposableObject
			- Addition: Some type converters (even JSON) for the AridityTeam.Util.Binary class
			- Modified: Changed MultiTextWriter's XML documentation
			- Modified: Overriden the "Dispose(bool)" method in MultiTextWriter
			- Modified: Added missing "DataContract" attributes to serializable types
			- Modified: Made string format parameters in each Logger functions nullable
			- Modified: Used the default type converters for the AridityTeam.Util.Binary class
			- Modified: Changed the package icon to differentiate this library from Aridity Cereon
			- Modified: Localized the default AridityTeam.Services.ServiceNotFoundException message
			- Modified: Made the IFormatProvider parameter in MultiTextWriter's constructor nullable
			- Modified: Fixed MultiTextWriter.Write(string, object?, object?) not passing the "arg1" parameter into it's writers
		</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\assets\ascorbic_icon.png" Pack="true" PackagePath="assets\" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net472'">
	    <PackageReference Include="Nullable" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
		<PackageReference Include="Microsoft.Bcl.Memory" />
		<PackageReference Include="Microsoft.Bcl.HashCode" />
		<PackageReference Include="System.Text.Json" />
    </ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<PackageReference Include="System.Net.Http" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="PolyType" />
		<PackageReference Include="System.Composition" />
		<PackageReference Include="System.ComponentModel.Composition" />
	</ItemGroup>
    <ItemGroup>
	    <Content Include="..\..\README.md" Pack="True" PackagePath="\" />
    </ItemGroup>
    <ItemGroup>
	    <Compile Update="SR.Designer.cs">
	        <DesignTime>True</DesignTime>
	        <AutoGen>True</AutoGen>
	        <DependentUpon>SR.resx</DependentUpon>
	    </Compile>
	    <EmbeddedResource Update="SR.resx">
	        <Generator>ResXFileCodeGenerator</Generator>
	        <LastGenOutput>SR.Designer.cs</LastGenOutput>
	    </EmbeddedResource>
    </ItemGroup>

</Project>
