<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFrameworks>net8.0;net472</TargetFrameworks>
	    <RootNamespace>MyAddIn</RootNamespace>
		<IsPackable>false</IsPackable>
    </PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="System.Composition" />
		<PackageReference Include="System.ComponentModel.Composition" />
		<ProjectReference Include="..\AridityTeam.Ascorbic\AridityTeam.Ascorbic.csproj" />
	</ItemGroup>

</Project>
