//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AridityTeam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AridityTeam.Cereon.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in &quot;{0}&quot; failed to initialize!.
        /// </summary>
        internal static string AddIn_FailedToInitialize {
            get {
                return ResourceManager.GetString("AddIn_FailedToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. Please contact Microsoft Support..
        /// </summary>
        internal static string InternalExceptionMessage {
            get {
                return ResourceManager.GetString("InternalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required service of type {0} is not registered..
        /// </summary>
        internal static string ServiceMgr_NotRegistered {
            get {
                return ResourceManager.GetString("ServiceMgr_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an instance of the {0} service..
        /// </summary>
        internal static string ServiceMissing {
            get {
                return ResourceManager.GetString("ServiceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected non-null value of type &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedNonNull {
            get {
                return ResourceManager.GetString("UnexpectedNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected null value of type &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedNull {
            get {
                return ResourceManager.GetString("UnexpectedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection must not be empty..
        /// </summary>
        internal static string Validation_CollectionEmpty {
            get {
                return ResourceManager.GetString("Validation_CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory &quot;{0}&quot; must exist..
        /// </summary>
        internal static string Validation_DirectoryMustExist {
            get {
                return ResourceManager.GetString("Validation_DirectoryMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The searched file &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        internal static string Validation_FileDoesNotExist {
            get {
                return ResourceManager.GetString("Validation_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file &quot;{0}&quot; must exist..
        /// </summary>
        internal static string Validation_FileMustExist {
            get {
                return ResourceManager.GetString("Validation_FileMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection must contain any duplicate elements..
        /// </summary>
        internal static string Validation_HasCollectionDuplicates {
            get {
                return ResourceManager.GetString("Validation_HasCollectionDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection must not contain any elements..
        /// </summary>
        internal static string Validation_HasNullElements {
            get {
                return ResourceManager.GetString("Validation_HasNullElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid directory path..
        /// </summary>
        internal static string Validation_InvalidDirectory {
            get {
                return ResourceManager.GetString("Validation_InvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid email address..
        /// </summary>
        internal static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid {0} enum value..
        /// </summary>
        internal static string Validation_InvalidEnum {
            get {
                return ResourceManager.GetString("Validation_InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid file path..
        /// </summary>
        internal static string Validation_InvalidFile {
            get {
                return ResourceManager.GetString("Validation_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid IP address..
        /// </summary>
        internal static string Validation_InvalidIP {
            get {
                return ResourceManager.GetString("Validation_InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not valid in the current state..
        /// </summary>
        internal static string Validation_InvalidOperationDefault {
            get {
                return ResourceManager.GetString("Validation_InvalidOperationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is in a invalid state..
        /// </summary>
        internal static string Validation_InvalidStateDefault {
            get {
                return ResourceManager.GetString("Validation_InvalidStateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid URL..
        /// </summary>
        internal static string Validation_InvalidURL {
            get {
                return ResourceManager.GetString("Validation_InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length must be between {0} and {1} characters..
        /// </summary>
        internal static string Validation_LengthMustBeInRange {
            get {
                return ResourceManager.GetString("Validation_LengthMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition must be false..
        /// </summary>
        internal static string Validation_MustBeFalse {
            get {
                return ResourceManager.GetString("Validation_MustBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition must be true..
        /// </summary>
        internal static string Validation_MustBeTrue {
            get {
                return ResourceManager.GetString("Validation_MustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected value: {0}, Actual value: {1}.
        /// </summary>
        internal static string Validation_NotEqualTo {
            get {
                return ResourceManager.GetString("Validation_NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be one of: {0}.
        /// </summary>
        internal static string Validation_NotOneOf {
            get {
                return ResourceManager.GetString("Validation_NotOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed: Condition returned false for {0}..
        /// </summary>
        internal static string Validation_OperationFailed {
            get {
                return ResourceManager.GetString("Validation_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number must be between 0 and 65535.
        /// </summary>
        internal static string Validation_PortInvalid {
            get {
                return ResourceManager.GetString("Validation_PortInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not match the required pattern: {0}.
        /// </summary>
        internal static string Validation_StringNotMatchingPattern {
            get {
                return ResourceManager.GetString("Validation_StringNotMatchingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        internal static string Validation_ValueEmpty {
            get {
                return ResourceManager.GetString("Validation_ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty or consist only of white-space characters..
        /// </summary>
        internal static string Validation_ValueEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("Validation_ValueEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1}..
        /// </summary>
        internal static string Validation_ValueMustBeInRange {
            get {
                return ResourceManager.GetString("Validation_ValueMustBeInRange", resourceCulture);
            }
        }
    }
}
